name: spotless check
permissions:
  pull-requests: write
on: [ pull_request ]
jobs:
  spotless-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run spotlessCheck
        run: ./gradlew spotlessCheck
      - name: Post Comment on Failure
        if: failure()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: Spotless Check Failed 🚨
          message: |
            Spotless check failed. Run the following command to fix it:
            ```
            ./gradlew spotlessApply
            ```
            Commit the changes to update this pull request.
